name: Validate Deployment to Prod

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SFDX CLI
      run: |
        npm install sfdx-cli --global
        sfdx --version

    - name: Authenticate to Salesforce
      env:
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      run: |
        echo $SFDX_AUTH_URL > sfdx_auth_url.txt
        sfdx force:auth:sfdxurl:store -f sfdx_auth_url.txt -a ValidationOrg

    - name: List Apex test classes
      run: |
        TEST_CLASSES=$(find force-app/main/default/classes/tests -name "*Test.cls" -exec basename {} .cls \; | tr '\n' ',' | sed 's/,$//')
        echo "Found test classes: $TEST_CLASSES"
        echo "TEST_CLASSES=$TEST_CLASSES" >> $GITHUB_ENV

    - name: Validate deployment
      run: |
        if [ -z "$TEST_CLASSES" ]; then
          sfdx force:source:deploy --checkonly -u ValidationOrg --sourcepath force-app
        else
          sfdx force:source:deploy --checkonly -u ValidationOrg --sourcepath force-app --testlevel RunSpecifiedTests --runtests $TEST_CLASSES
        fi

        DEPLOY_EXIT_CODE=${PIPESTATUS[0]}

        if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
          echo "Deployment validation failed. Extracting error messages..."
          cat deploy_output.log | grep -A 10 -E "(ERROR|Failed|INVALID|Unhandled)" || echo "No specific error message found."
          exit $DEPLOY_EXIT_CODE
        else
          echo "Deployment validation succeeded."
        fi
